refresh configure scripts

diff --git a/src/modules/rlm_sqlippool/configure b/src/modules/rlm_sqlippool/configure
--- a/src/modules/rlm_sqlippool/configure
+++ b/src/modules/rlm_sqlippool/configure
@@ -585,9 +585,9 @@ PACKAGE_URL=
 ac_unique_file="rlm_sqlippool.c"
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
-targetname
 mod_cflags
 mod_ldflags
+targetname
 target_alias
 host_alias
 build_alias
@@ -1330,6 +1330,11 @@ fi
 ## ------------------------ ##
 ## Autoconf initialization. ##
 ## ------------------------ ##
+
+echo
+echo Running tests for rlm_sqlippool
+echo
+
 cat >config.log <<_ACEOF
 This file contains any messages produced by compilers while
 running configure, to aid debugging if configure makes a mistake.
@@ -1687,6 +1692,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
 # Check whether --with-rlm_sqlippool was given.
 if test "${with_rlm_sqlippool+set}" = set; then :
   withval=$with_rlm_sqlippool;
@@ -1694,17 +1700,67 @@ fi
 
 
 
-if test x$with_rlm_sqlippool != xno; then
+
+fail=
+fr_status=
+fr_features=
+: > "config.report"
+: > "config.report.tmp"
+
+
+
+if test x"$with_modname_useropt" != xno; then
+
+
 
 
 	targetname=rlm_sqlippool
 else
 	targetname=
 	echo \*\*\* module rlm_sqlippool is disabled.
+
+
+fr_status="disabled"
+
 fi
+
+if test x"$fail" != x""; then
+	targetname=""
+
+
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: silently not building rlm_sqlippool." >&5
+$as_echo "$as_me: WARNING: silently not building rlm_sqlippool." >&2;}
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: FAILURE: rlm_sqlippool requires: $fail." >&5
+$as_echo "$as_me: WARNING: FAILURE: rlm_sqlippool requires: $fail." >&2;};
+		fail="$(echo $fail)"
+
+
+fr_status="skipping (requires $fail)"
+
+		fr_features=
+
+else
+
+
+fr_status="OK"
+
+fi
+
+if test x"$fr_features" = x""; then
+	$as_echo "$fr_status" > "config.report"
+else
+	$as_echo_n "$fr_status ... " > "config.report"
+	cat "config.report.tmp" >> "config.report"
+fi
+
+rm "config.report.tmp"
+
+
+
 
 mod_ldflags="$SMART_LIBS"
 mod_cflags="$SMART_CPPFLAGS"
+
 
 
 
