refresh configure scripts

diff --git a/src/modules/rlm_cache/configure b/src/modules/rlm_cache/configure
--- a/src/modules/rlm_cache/configure
+++ b/src/modules/rlm_cache/configure
@@ -1264,7 +1264,7 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --without-rlm_cache     build without rlm_cache
+  --without-rlm_cache     build without module to cache attributes
 
 Some influential environment variables:
   CC          C compiler command
@@ -1354,6 +1354,11 @@ fi
 ## ------------------------ ##
 ## Autoconf initialization. ##
 ## ------------------------ ##
+
+echo
+echo Running tests for rlm_cache
+echo
+
 
 # ac_fn_c_try_compile LINENO
 # --------------------------
@@ -1750,6 +1755,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
 # Check whether --with-rlm_cache was given.
 if test "${with_rlm_cache+set}" = set; then :
   withval=$with_rlm_cache;
@@ -1757,13 +1763,22 @@ fi
 
 
 
-fail=
 SMART_LIBS=
 SMART_CLFAGS=
 
-if test x$with_rlm_cache != xno; then
 
-	ac_ext=c
+fail=
+fr_status=
+fr_features=
+: > "config.report"
+: > "config.report.tmp"
+
+
+
+if test x"$with_rlm_cache" != xno; then
+
+
+ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -2553,21 +2568,21 @@ ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $
 ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
-	mysubdirs=
-	if test "x$EXPERIMENTAL" = "xyes"; then
-	  for foo in `find ./drivers -name configure -print`; do
-	    bar=`echo $foo | sed 's%/configure$%%g'`
-	    mysubdirs="$mysubdirs $bar"
-	  done
-	else
-	  for foo in `cat stable`; do
-	    mysubdirs="$mysubdirs ./drivers/$foo"
-	  done
-	fi
+mysubdirs=
+if test "x$EXPERIMENTAL" = "xyes"; then
+	for foo in `find ./drivers -name configure -print`; do
+		bar=`echo $foo | sed 's%/configure$%%g'`
+		mysubdirs="$mysubdirs $bar"
+	done
+else
+	for foo in `cat stable`; do
+		mysubdirs="$mysubdirs ./drivers/$foo"
+	done
+fi
 
-		ln -s ../../../install-sh install-sh
+ln -s ../../../install-sh install-sh
 
-					ac_aux_dir=
+ac_aux_dir=
 for ac_dir in "$srcdir" "$srcdir/.." "$srcdir/../.."; do
   if test -f "$ac_dir/install-sh"; then
     ac_aux_dir=$ac_dir
@@ -2600,14 +2615,51 @@ ac_configure="$SHELL $ac_aux_dir/configure"  # Please don't use this var.
 
 subdirs="$subdirs $mysubdirs"
 
-	rm install-sh
+rm install-sh
 
 
 	targetname=rlm_cache
 else
 	targetname=
 	echo \*\*\* module rlm_cache is disabled.
+
+
+fr_status="disabled"
+
 fi
+
+if test x"$fail" != x""; then
+	targetname=""
+
+
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: silently not building rlm_cache." >&5
+$as_echo "$as_me: WARNING: silently not building rlm_cache." >&2;}
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: FAILURE: rlm_cache requires: $fail." >&5
+$as_echo "$as_me: WARNING: FAILURE: rlm_cache requires: $fail." >&2;};
+		fail="$(echo $fail)"
+
+
+fr_status="skipping (requires $fail)"
+
+		fr_features=
+
+else
+
+
+fr_status="OK"
+
+fi
+
+if test x"$fr_features" = x""; then
+	$as_echo "$fr_status" > "config.report"
+else
+	$as_echo_n "$fr_status ... " > "config.report"
+	cat "config.report.tmp" >> "config.report"
+fi
+
+rm "config.report.tmp"
+
+
 
 
 ac_config_files="$ac_config_files all.mk"
diff --git a/src/modules/rlm_radutmp/configure b/src/modules/rlm_radutmp/configure
--- a/src/modules/rlm_radutmp/configure
+++ b/src/modules/rlm_radutmp/configure
@@ -622,9 +622,9 @@ ac_includes_default="\
 
 ac_subst_vars='LTLIBOBJS
 LIBOBJS
-targetname
 mod_cflags
 mod_ldflags
+targetname
 EGREP
 GREP
 CPP
@@ -1305,7 +1305,8 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
-  --without-rlm_radutmp   build without rlm_radutmp
+  --without-rlm_radutmp   build without ability to maintain utmp-style
+                          sessions
 
 Some influential environment variables:
   CC          C compiler command
@@ -1396,6 +1397,11 @@ fi
 ## ------------------------ ##
 ## Autoconf initialization. ##
 ## ------------------------ ##
+
+echo
+echo Running tests for rlm_radutmp
+echo
+
 
 # ac_fn_c_try_compile LINENO
 # --------------------------
@@ -1989,6 +1995,7 @@ ac_compiler_gnu=$ac_cv_c_compiler_gnu
 
 
 
+
 # Check whether --with-rlm_radutmp was given.
 if test "${with_rlm_radutmp+set}" = set; then :
   withval=$with_rlm_radutmp;
@@ -1996,9 +2003,19 @@ fi
 
 
 
-if test x$with_rlm_radutmp != xno; then
 
-	ac_ext=c
+fail=
+fr_status=
+fr_features=
+: > "config.report"
+: > "config.report.tmp"
+
+
+
+if test x"$with_rlm_radutmp" != xno; then
+
+
+ac_ext=c
 ac_cpp='$CPP $CPPFLAGS'
 ac_compile='$CC -c $CFLAGS $CPPFLAGS conftest.$ac_ext >&5'
 ac_link='$CC -o conftest$ac_exeext $CFLAGS $CPPFLAGS $LDFLAGS conftest.$ac_ext $LIBS >&5'
@@ -3198,11 +3215,50 @@ fi
 done
 
 
+
 	targetname=rlm_radutmp
 else
 	targetname=
 	echo \*\*\* module rlm_radutmp is disabled.
+
+
+fr_status="disabled"
+
 fi
+
+if test x"$fail" != x""; then
+	targetname=""
+
+
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: silently not building rlm_radutmp." >&5
+$as_echo "$as_me: WARNING: silently not building rlm_radutmp." >&2;}
+		{ $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: FAILURE: rlm_radutmp requires: $fail." >&5
+$as_echo "$as_me: WARNING: FAILURE: rlm_radutmp requires: $fail." >&2;};
+		fail="$(echo $fail)"
+
+
+fr_status="skipping (requires $fail)"
+
+		fr_features=
+
+else
+
+
+fr_status="OK"
+
+fi
+
+if test x"$fr_features" = x""; then
+	$as_echo "$fr_status" > "config.report"
+else
+	$as_echo_n "$fr_status ... " > "config.report"
+	cat "config.report.tmp" >> "config.report"
+fi
+
+rm "config.report.tmp"
+
+
+
 
 
 
