more comments on antora and asciidoc

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3247,8 +3247,8 @@ fi
 
 
 if test "x$ac_cv_path_ANTORA" = "x"; then
-  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: antora not found - Please install if you want build the site" >&5
-printf "%s\n" "$as_me: WARNING: antora not found - Please install if you want build the site" >&2;}
+  { printf "%s\n" "$as_me:${as_lineno-$LINENO}: WARNING: antora not found - Please install if you want build the docs" >&5
+printf "%s\n" "$as_me: WARNING: antora not found - Please install if you want build the docs" >&2;}
 fi
 
 # Check whether --enable-developer was given.
