Forward port all the interesting things from FreeRADIUS 1.0.x in the Debian archive to CVS HEAD. This brings dpatch-2 support, even though there aren't any dpatches needed yet. (Changelog entry for 1.1.0~pre0~cvs has become long and unwieldly, may need to refactor based on the 1.0.x debian-release changelogs.)

diff --git a/debian/freeradius.init b/debian/freeradius.init
--- a/debian/freeradius.init
+++ b/debian/freeradius.init
@@ -1,43 +1,47 @@
 #!/bin/sh
 # Start/stop the FreeRADIUS daemon.
 
-set -u
+set -e
 
-prog="freeradius"
-program="/usr/sbin/freeradius"
-pidfile="/var/run/freeradius/freeradius.pid"
-descr="FreeRADIUS daemon"
+PROG="freeradius"
+PROGRAM="/usr/sbin/freeradius"
+PIDFILE="/var/run/freeradius/freeradius.pid"
+DESCR="FreeRADIUS daemon"
 
-test -f $program || exit 0
+test -f $PROGRAM || exit 0
 
 case "$1" in
-start)	echo -n "Starting $descr: "
-        start-stop-daemon --start --quiet --pidfile $pidfile --exec $program
-	if [ $? = 0 ]; then
-		echo "$prog."
-	else
-		echo "(failed!  run '$program -x' to find out why.)"
-		exit 1
-	fi
-	;;
-stop)	echo -n "Stopping $descr: "
-        start-stop-daemon --stop --quiet --pidfile $pidfile
-        echo "$prog."
-        ;;
-restart) echo -n "Restarting $descr: "
+	start)
+		echo -n "Starting $DESCR: "
+		start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $PROGRAM
+		if [ $? = 0 ]; then
+			echo "$PROG."
+		else
+			echo "(failed!  run '$PROGRAM -x' to find out why.)"
+			exit 1
+		fi
+		;;
+	stop)
+		echo -n "Stopping $DESCR: "
+		start-stop-daemon --stop --quiet --pidfile $PIDFILE
+		echo "$PROG."
+		;;
+	restart)
+		echo -n "Restarting $DESCR: "
 		$0 stop
 		sleep 2
 		$0 start
-        ;;
-reload|force-reload) 
-		echo -n "Reloading configuration files for $descr"
-		start-stop-daemon --stop --signal 1 --quiet --pidfile $pidfile
+		;;
+	reload | force-reload) 
+		echo -n "Reloading configuration files for $DESCR"
+		start-stop-daemon --stop --signal 1 --quiet --pidfile $PIDFILE
 		sleep 2
-		ps --pid $(cat $pidfile) > /dev/null || exit 1
-        echo "."
-        ;;
-*)	echo "Usage: /etc/init.d/freeradius start|stop|restart|reload|force-reload"
-        exit 1 
-        ;;
+		ps --pid $(cat $PIDFILE) > /dev/null || exit 1
+		echo "."
+		;;
+	*)
+		echo "Usage: /etc/init.d/freeradius start|stop|restart|reload|force-reload"
+		exit 1 
 esac
+
 exit 0
