profiling: multi-server test makefile updated to be able to profile with gperftools, currently using start_gperftools_profiling.sh placeholder script

diff --git a/src/tests/multi-server/tests/ldap/template.yml.j2 b/src/tests/multi-server/tests/ldap/template.yml.j2
--- a/src/tests/multi-server/tests/ldap/template.yml.j2
+++ b/src/tests/multi-server/tests/ldap/template.yml.j2
@@ -34,7 +34,12 @@ states:
               printf "  MAX_REQUESTS:     %s\n" "$TEST_LOADGEN_MAX_REQUESTS"
 
               if [ "$PROFILING" = "yes" ]; then
-                source /etc/freeradius/start_valgrind_profiling.sh
+                START_SCRIPT="/etc/freeradius/start_$PROFILING_TOOL"_profiling.sh
+                if [ ! -r "$START_SCRIPT" ]; then
+                  echo "Profiling start script not found: $START_SCRIPT"
+                  exit 1
+                fi
+                source "$START_SCRIPT"
               else
                 exec freeradius -f -l stdout -S resources.talloc_skip_cleanup=yes
               fi
