Squashed changes from patch-5 into dpd-improvements

diff --git a/src/main/radsecret b/src/main/radsecret
--- a/src/main/radsecret
+++ b/src/main/radsecret
@@ -1,7 +1,14 @@
-#!/usr/bin/env perl
+#!/bin/sh
 #
 #  A tool which generates strong shared secrets.
 #
-use Convert::Base32;
-use Crypt::URandom();
-print join('-', unpack("(A4)*", lc encode_base32(Crypt::URandom::urandom(12)))), "\n";
+openssl rand -base64 12 2>/dev/null && exit 0
+
+(dd if=/dev/urandom bs=1 count=12 2>/dev/null | base64 2>/dev/null) && exit 0
+
+(dd if=/dev/urandom bs=1 count=12 2>/dev/null | base32 2>/dev/null) && exit 0
+
+(dd if=/dev/urandom bs=1 count=12 2>/dev/null | (hexdump -ve '/1 "%02x"' && echo 2>/dev/null)) && exit 0
+
+echo "Failed finding 'openssl', 'base64', 'base32', or 'hexdump' tools".
+exit 1
