Integrated phil@bolthole.com's patch for Oracle8i.  It's heavily hacked in, so it may not be correct, still.

diff --git a/src/modules/rlm_sql/drivers/rlm_sql_oracle/configure b/src/modules/rlm_sql/drivers/rlm_sql_oracle/configure
--- a/src/modules/rlm_sql/drivers/rlm_sql_oracle/configure
+++ b/src/modules/rlm_sql/drivers/rlm_sql_oracle/configure
@@ -555,7 +555,72 @@ else
 fi
 rm -f conftest*
 
-				if test "x$ORACLE_INCLUDE" = "x"; then
+	# Look for Oracle8i.
+	if test "x$ORACLE_INCLUDE" = "x"; then
+		old_CFLAGS="$CFLAGS"
+
+		
+
+if test "x$LOCATE" != "x"; then
+        DIRS=
+  file=oci.h
+
+  for x in `${LOCATE} $file 2>/dev/null`; do
+                                        base=`echo $x | sed "s%/${file}%%"`
+    if test "x$x" = "x$base"; then
+      continue;
+    fi
+
+    dir=`${DIRNAME} $x 2>/dev/null`
+                exclude=`echo ${dir} | ${GREP} /home`
+    if test "x$exclude" != "x"; then
+      continue
+    fi
+
+                    already=`echo \$oracle_home_dir ${DIRS} | ${GREP} ${dir}`
+    if test "x$already" = "x"; then
+      DIRS="$DIRS $dir"
+    fi
+  done
+fi
+
+eval "oracle_home_dir=\"\$oracle_home_dir $DIRS\""
+
+
+		for try in /usr/local/include/oracle /usr/local/oracle/include $oracle_include_dir; do
+			CFLAGS="$old_CFLAGS -I${try}/rdbms/demo ${try}/rdbms/public -I${try}/plsql/public -I${try}/network/public -I${try}/oci/include"
+			cat > conftest.$ac_ext <<EOF
+#line 594 "configure"
+#include "confdefs.h"
+#include <oci.h>
+int main() {
+ int a = 1; 
+; return 0; }
+EOF
+if { (eval echo configure:601: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+  rm -rf conftest*
+  ORACLE_HOME=$try
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  ORACLE_HOME=
+			
+fi
+rm -f conftest*
+			if test "x$ORACLE_HOME" != "x"; then
+				break;
+			fi
+		done
+		CFLAGS="$old_CFLAGS"
+
+		if test "x$ORACLE_HOME" != "x"; then
+			ORACLE_INCLUDE="-I${ORACLE_HOME}/rdbms/demo ${ORACLE_HOME}/rdbms/public -I${ORACLE_HOME}/plsql/public -I${ORACLE_HOME}/network/public -I${ORACLE_HOME}/oci/include"
+		fi
+	fi     ##  this section sets $ORACLE_HOME, if found.
+
+	# not Oracle8i, try older.
+	if test "x$ORACLE_INCLUDE" = "x"; then
 		old_CFLAGS="$CFLAGS"
 
 		
@@ -589,14 +654,14 @@ eval "oracle_include_dir=\"\$oracle_include_dir $DIRS\""
 		for try in /usr/local/include/oracle /usr/local/oracle/include $oracle_include_dir; do
 			CFLAGS="$old_CFLAGS -I$try"
 			cat > conftest.$ac_ext <<EOF
-#line 593 "configure"
+#line 658 "configure"
 #include "confdefs.h"
 #include <oci.h>
 int main() {
  int a = 1; 
 ; return 0; }
 EOF
-if { (eval echo configure:600: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
+if { (eval echo configure:665: \"$ac_compile\") 1>&5; (eval $ac_compile) 2>&5; }; then
   rm -rf conftest*
   ORACLE_INCLUDE="-I$try"
 else
@@ -616,20 +681,23 @@ rm -f conftest*
 
 	if test "x$ORACLE_INCLUDE" = "x"; then
 		echo "$ac_t""no" 1>&6
-		echo "configure: warning: oracle headers not found.  Use --with-oracle-include-dir=<path>." 1>&2
+		echo "configure: warning: oracle headers not found.  Use --with-oracle-home-dir=<path>." 1>&2
 		targetname=   # disabled module
 	else
 		sql_oracle_cflags="${sql_oracle_cflags} ${ORACLE_INCLUDE}"
 		echo "$ac_t""yes" 1>&6
 
-						
 
-		## Somebody who's actually coded oracle stuff:  please fix this.
-		for oracle_library in oracleclient libclient8 libclntsh; do
+		## is this set, from above?
+		if test "x$ORACLE_HOME" != "x"; then
+			## we must have an Oracle8i tree
 
+			# FIXME: we might do some checking, just to be nice
+			ORACLE_LIBS="-L$ORACLE_HOME/lib -lclntsh -lwtc8 -lm"
 
-			echo $ac_n "checking for oracle_init in -l$oracle_library""... $ac_c" 1>&6
-echo "configure:633: checking for oracle_init in -l$oracle_library" >&5
+		else
+			echo $ac_n "checking for oracle_init in -loracleclient""... $ac_c" 1>&6
+echo "configure:701: checking for oracle_init in -loracleclient" >&5
 
 												old_LIBS="$LIBS"
 
@@ -637,7 +705,7 @@ echo "configure:633: checking for oracle_init in -l$oracle_library" >&5
 
 if test "x$LOCATE" != "x"; then
         DIRS=
-  file=${oracle_library}.so
+  file=oracleclient.so
 
   for x in `${LOCATE} $file 2>/dev/null`; do
                                         base=`echo $x | sed "s%/${file}%%"`
@@ -664,7 +732,7 @@ eval "oracle_lib_dir=\"\$oracle_lib_dir $DIRS\""
 
 if test "x$LOCATE" != "x"; then
         DIRS=
-  file=${oracle_library}.a
+  file=oracleclient.a
 
   for x in `${LOCATE} $file 2>/dev/null`; do
                                         base=`echo $x | sed "s%/${file}%%"`
@@ -689,18 +757,18 @@ eval "oracle_lib_dir=\"\$oracle_lib_dir $DIRS\""
 
 
 			for try in /usr/lib/oracle /usr/local/lib/oracle /usr/local/oracle/lib $oracle_lib_dir; do
-				LIBS="$old_LIBS -L$try -l${oracle_library}"
+				LIBS="$old_LIBS -L$try -loracleclient"
 				cat > conftest.$ac_ext <<EOF
-#line 695 "configure"
+#line 763 "configure"
 #include "confdefs.h"
 extern char oracle_init();
 int main() {
  oracle_init()
 ; return 0; }
 EOF
-if { (eval echo configure:702: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+if { (eval echo configure:770: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
   rm -rf conftest*
-  ORACLE_LIBS="-L$try -l${oracle_library}"
+  ORACLE_LIBS="-L$try -loracleclient"
 else
   echo "configure: failed program was:" >&5
   cat conftest.$ac_ext >&5
@@ -723,7 +791,8 @@ rm -f conftest*
 				echo "$ac_t""yes" 1>&6
 				break
 			fi
-		done
+		fi
+
 		if test "x$ORACLE_LIBS" != "x"; then
 			echo "configure: warning: oracle libraries not found.  Use --with-oracle-lib-dir=<path>." 1>&2
 			targetname=   # disabled module
