Corrected error messages, based on comments from 	Thomas Jalsovsky <admin@postel.sk>

diff --git a/src/modules/rlm_sql/drivers/rlm_sql_mysql/configure b/src/modules/rlm_sql/drivers/rlm_sql_mysql/configure
--- a/src/modules/rlm_sql/drivers/rlm_sql_mysql/configure
+++ b/src/modules/rlm_sql/drivers/rlm_sql_mysql/configure
@@ -527,7 +527,7 @@ else
 fi
 
 
-# From configure.in Revision: 1.2 
+# From configure.in Revision: 1.3 
 
 
 # Check whether --with-mysql-include-dir or --without-mysql-include-dir was given.
@@ -705,7 +705,7 @@ rm -f conftest*
 						if test "x$MYSQL_LIBS" = "x"; then
 			echo "$ac_t""no" 1>&6
 			MYSQL_INCLUDE=
-			echo "configure: warning: mysql headers not found.  Use --with-mysql-include-dir=<path>." 1>&2
+			echo "configure: warning: mysql libraries not found.  Use --with-mysql-lib-dir=<path>." 1>&2
 			targetname=   # disabled module
 		else
 			echo "$ac_t""yes" 1>&6 
