Regenerate after changes to acinclude.m4

diff --git a/src/modules/rlm_krb5/configure b/src/modules/rlm_krb5/configure
--- a/src/modules/rlm_krb5/configure
+++ b/src/modules/rlm_krb5/configure
@@ -2482,10 +2482,66 @@ ac_safe=`echo "krb5.h" | sed 'y%./+-%__pm%'`
 echo "$as_me:$LINENO: checking for krb5.h" >&5
 echo $ECHO_N "checking for krb5.h... $ECHO_C" >&6
 
+old_CFLAGS="$CFLAGS"
 smart_include=
 smart_include_dir=
 
-  old_CFLAGS="$CFLAGS"
+if test "x$smart_try_dir" != "x"; then
+  for try in $smart_try_dir; do
+    CFLAGS="$old_CFLAGS -I$try"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+		    #include <krb5.h>
+int
+main ()
+{
+ int a = 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  smart_include="-I$try"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+smart_include=
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+    if test "x$smart_include" != "x"; then
+      break;
+    fi
+    CFLAGS="$old_CFLAGS"
+  done
+fi
+
+if test "x$smart_include" = "x"; then
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -2531,8 +2587,9 @@ sed 's/^/| /' conftest.$ac_ext >&5
 smart_include=
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
 
-  if test "x$smart_include" = "x"; then
+if test "x$smart_include" = "x"; then
 
 
 if test "x$LOCATE" != "x"; then
@@ -2561,17 +2618,16 @@ fi
 eval "smart_include_dir=\"\$smart_include_dir $DIRS\""
 
 
-    for try in $smart_try_dir $smart_include_dir /usr/local/include/ /opt/include; do
-      CFLAGS="$old_CFLAGS -I$try"
-
-      cat >conftest.$ac_ext <<_ACEOF
+  for try in $smart_include_dir /usr/local/include /opt/include; do
+    CFLAGS="$old_CFLAGS -I$try"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-		       #include <krb5.h>
+		    #include <krb5.h>
 int
 main ()
 {
@@ -2609,22 +2665,21 @@ sed 's/^/| /' conftest.$ac_ext >&5
 smart_include=
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-
-      if test "x$smart_include" != "x"; then
-        break;
-      fi
-    done
+    if test "x$smart_include" != "x"; then
+      break;
+    fi
     CFLAGS="$old_CFLAGS"
-  fi
+  done
+fi
 
-        if test "x$smart_include" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+if test "x$smart_include" != "x"; then
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    eval "ac_cv_header_$ac_safe=yes"
-    CFLAGS="$old_CFLAGS $smart_include"
-    SMART_CFLAGS="$SMART_CFLAGS $smart_include"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+  eval "ac_cv_header_$ac_safe=yes"
+  CFLAGS="$old_CFLAGS $smart_include"
+  SMART_CFLAGS="$SMART_CFLAGS $smart_include"
+else
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -2638,11 +2693,66 @@ sm_func_safe=`echo "krb5_encrypt_data" | sed 'y%./+-%__p_%'`
 echo "$as_me:$LINENO: checking for krb5_encrypt_data in -lk5crypto" >&5
 echo $ECHO_N "checking for krb5_encrypt_data in -lk5crypto... $ECHO_C" >&6
 
+old_LIBS="$LIBS"
 smart_lib=
 smart_lib_dir=
 
-  old_LIBS="$LIBS"
-  LIBS="$LIBS -lk5crypto"
+if test "x$smart_try_dir" != "x"; then
+  for try in $smart_try_dir; do
+    LIBS="-L$try -lk5crypto $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+extern char krb5_encrypt_data();
+int
+main ()
+{
+ krb5_encrypt_data()
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  smart_lib="-L$try -lk5crypto"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
+    LIBS="$old_LIBS"
+  done
+fi
+
+if test "x$smart_lib" = "x"; then
+  LIBS="-lk5crypto $old_LIBS"
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -2687,8 +2797,10 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+  LIBS="$old_LIBS"
+fi
 
-  if test "x$smart_lib" = "x"; then
+if test "x$smart_lib" = "x"; then
 
 
 if test "x$LOCATE" != "x"; then
@@ -2744,10 +2856,9 @@ fi
 eval "smart_lib_dir=\"\$smart_lib_dir $DIRS\""
 
 
-    for try in $smart_try_dir $smart_lib_dir /usr/local/lib/ /opt/lib; do
-      LIBS="$old_LIBS -L$try -lk5crypto"
-
-      cat >conftest.$ac_ext <<_ACEOF
+  for try in $smart_lib_dir /usr/local/lib /opt/lib; do
+    LIBS="-L$try -lk5crypto $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -2791,21 +2902,21 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-      if test "x$smart_lib" != "x"; then
-        break;
-      fi
-    done
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
     LIBS="$old_LIBS"
-  fi
+  done
+fi
 
-        if test "x$smart_lib" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+if test "x$smart_lib" != "x"; then
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
-    LIBS="$old_LIBS $smart_lib"
-    SMART_LIBS="$SMART_LIBS $smart_lib"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+  eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
+  LIBS="$smart_lib $old_LIBS"
+  SMART_LIBS="$smart_lib $SMART_LIBS"
+else
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -2820,11 +2931,66 @@ sm_func_safe=`echo "DH_new" | sed 'y%./+-%__p_%'`
 echo "$as_me:$LINENO: checking for DH_new in -lcrypto" >&5
 echo $ECHO_N "checking for DH_new in -lcrypto... $ECHO_C" >&6
 
+old_LIBS="$LIBS"
 smart_lib=
 smart_lib_dir=
 
-  old_LIBS="$LIBS"
-  LIBS="$LIBS -lcrypto"
+if test "x$smart_try_dir" != "x"; then
+  for try in $smart_try_dir; do
+    LIBS="-L$try -lcrypto $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+extern char DH_new();
+int
+main ()
+{
+ DH_new()
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  smart_lib="-L$try -lcrypto"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
+    LIBS="$old_LIBS"
+  done
+fi
+
+if test "x$smart_lib" = "x"; then
+  LIBS="-lcrypto $old_LIBS"
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -2869,8 +3035,10 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+  LIBS="$old_LIBS"
+fi
 
-  if test "x$smart_lib" = "x"; then
+if test "x$smart_lib" = "x"; then
 
 
 if test "x$LOCATE" != "x"; then
@@ -2926,10 +3094,9 @@ fi
 eval "smart_lib_dir=\"\$smart_lib_dir $DIRS\""
 
 
-    for try in $smart_try_dir $smart_lib_dir /usr/local/lib/ /opt/lib; do
-      LIBS="$old_LIBS -L$try -lcrypto"
-
-      cat >conftest.$ac_ext <<_ACEOF
+  for try in $smart_lib_dir /usr/local/lib /opt/lib; do
+    LIBS="-L$try -lcrypto $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -2973,21 +3140,21 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-      if test "x$smart_lib" != "x"; then
-        break;
-      fi
-    done
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
     LIBS="$old_LIBS"
-  fi
+  done
+fi
 
-        if test "x$smart_lib" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+if test "x$smart_lib" != "x"; then
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
-    LIBS="$old_LIBS $smart_lib"
-    SMART_LIBS="$SMART_LIBS $smart_lib"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+  eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
+  LIBS="$smart_lib $old_LIBS"
+  SMART_LIBS="$smart_lib $SMART_LIBS"
+else
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -3007,11 +3174,66 @@ sm_func_safe=`echo "set_com_err_hook" | sed 'y%./+-%__p_%'`
 echo "$as_me:$LINENO: checking for set_com_err_hook in -lcom_err" >&5
 echo $ECHO_N "checking for set_com_err_hook in -lcom_err... $ECHO_C" >&6
 
+old_LIBS="$LIBS"
 smart_lib=
 smart_lib_dir=
 
-  old_LIBS="$LIBS"
-  LIBS="$LIBS -lcom_err"
+if test "x$smart_try_dir" != "x"; then
+  for try in $smart_try_dir; do
+    LIBS="-L$try -lcom_err $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+extern char set_com_err_hook();
+int
+main ()
+{
+ set_com_err_hook()
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  smart_lib="-L$try -lcom_err"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
+    LIBS="$old_LIBS"
+  done
+fi
+
+if test "x$smart_lib" = "x"; then
+  LIBS="-lcom_err $old_LIBS"
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -3056,8 +3278,10 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+  LIBS="$old_LIBS"
+fi
 
-  if test "x$smart_lib" = "x"; then
+if test "x$smart_lib" = "x"; then
 
 
 if test "x$LOCATE" != "x"; then
@@ -3113,10 +3337,9 @@ fi
 eval "smart_lib_dir=\"\$smart_lib_dir $DIRS\""
 
 
-    for try in $smart_try_dir $smart_lib_dir /usr/local/lib/ /opt/lib; do
-      LIBS="$old_LIBS -L$try -lcom_err"
-
-      cat >conftest.$ac_ext <<_ACEOF
+  for try in $smart_lib_dir /usr/local/lib /opt/lib; do
+    LIBS="-L$try -lcom_err $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -3160,21 +3383,21 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-      if test "x$smart_lib" != "x"; then
-        break;
-      fi
-    done
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
     LIBS="$old_LIBS"
-  fi
+  done
+fi
 
-        if test "x$smart_lib" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+if test "x$smart_lib" != "x"; then
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
-    LIBS="$old_LIBS $smart_lib"
-    SMART_LIBS="$SMART_LIBS $smart_lib"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+  eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
+  LIBS="$smart_lib $old_LIBS"
+  SMART_LIBS="$smart_lib $SMART_LIBS"
+else
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -3190,11 +3413,66 @@ sm_func_safe=`echo "krb5_init_context" | sed 'y%./+-%__p_%'`
 echo "$as_me:$LINENO: checking for krb5_init_context in -lkrb5" >&5
 echo $ECHO_N "checking for krb5_init_context in -lkrb5... $ECHO_C" >&6
 
+old_LIBS="$LIBS"
 smart_lib=
 smart_lib_dir=
 
-  old_LIBS="$LIBS"
-  LIBS="$LIBS -lkrb5"
+if test "x$smart_try_dir" != "x"; then
+  for try in $smart_try_dir; do
+    LIBS="-L$try -lkrb5 $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+extern char krb5_init_context();
+int
+main ()
+{
+ krb5_init_context()
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  smart_lib="-L$try -lkrb5"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
+    LIBS="$old_LIBS"
+  done
+fi
+
+if test "x$smart_lib" = "x"; then
+  LIBS="-lkrb5 $old_LIBS"
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -3239,8 +3517,10 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+  LIBS="$old_LIBS"
+fi
 
-  if test "x$smart_lib" = "x"; then
+if test "x$smart_lib" = "x"; then
 
 
 if test "x$LOCATE" != "x"; then
@@ -3296,10 +3576,9 @@ fi
 eval "smart_lib_dir=\"\$smart_lib_dir $DIRS\""
 
 
-    for try in $smart_try_dir $smart_lib_dir /usr/local/lib/ /opt/lib; do
-      LIBS="$old_LIBS -L$try -lkrb5"
-
-      cat >conftest.$ac_ext <<_ACEOF
+  for try in $smart_lib_dir /usr/local/lib /opt/lib; do
+    LIBS="-L$try -lkrb5 $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -3343,21 +3622,21 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-      if test "x$smart_lib" != "x"; then
-        break;
-      fi
-    done
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
     LIBS="$old_LIBS"
-  fi
+  done
+fi
 
-        if test "x$smart_lib" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+if test "x$smart_lib" != "x"; then
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
-    LIBS="$old_LIBS $smart_lib"
-    SMART_LIBS="$SMART_LIBS $smart_lib"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+  eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
+  LIBS="$smart_lib $old_LIBS"
+  SMART_LIBS="$smart_lib $SMART_LIBS"
+else
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
diff --git a/src/modules/rlm_perl/configure b/src/modules/rlm_perl/configure
--- a/src/modules/rlm_perl/configure
+++ b/src/modules/rlm_perl/configure
@@ -2463,10 +2463,66 @@ ac_safe=`echo "EXTERN.h" | sed 'y%./+-%__pm%'`
 echo "$as_me:$LINENO: checking for EXTERN.h" >&5
 echo $ECHO_N "checking for EXTERN.h... $ECHO_C" >&6
 
+old_CFLAGS="$CFLAGS"
 smart_include=
 smart_include_dir=
 
-  old_CFLAGS="$CFLAGS"
+if test "x$smart_try_dir" != "x"; then
+  for try in $smart_try_dir; do
+    CFLAGS="$old_CFLAGS -I$try"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+		    #include <EXTERN.h>
+int
+main ()
+{
+ int a = 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  smart_include="-I$try"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+smart_include=
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+    if test "x$smart_include" != "x"; then
+      break;
+    fi
+    CFLAGS="$old_CFLAGS"
+  done
+fi
+
+if test "x$smart_include" = "x"; then
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -2512,8 +2568,9 @@ sed 's/^/| /' conftest.$ac_ext >&5
 smart_include=
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
 
-  if test "x$smart_include" = "x"; then
+if test "x$smart_include" = "x"; then
 
 
 if test "x$LOCATE" != "x"; then
@@ -2542,17 +2599,16 @@ fi
 eval "smart_include_dir=\"\$smart_include_dir $DIRS\""
 
 
-    for try in $smart_try_dir $smart_include_dir /usr/local/include/ /opt/include; do
-      CFLAGS="$old_CFLAGS -I$try"
-
-      cat >conftest.$ac_ext <<_ACEOF
+  for try in $smart_include_dir /usr/local/include /opt/include; do
+    CFLAGS="$old_CFLAGS -I$try"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-		       #include <EXTERN.h>
+		    #include <EXTERN.h>
 int
 main ()
 {
@@ -2590,22 +2646,21 @@ sed 's/^/| /' conftest.$ac_ext >&5
 smart_include=
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-
-      if test "x$smart_include" != "x"; then
-        break;
-      fi
-    done
+    if test "x$smart_include" != "x"; then
+      break;
+    fi
     CFLAGS="$old_CFLAGS"
-  fi
+  done
+fi
 
-        if test "x$smart_include" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+if test "x$smart_include" != "x"; then
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    eval "ac_cv_header_$ac_safe=yes"
-    CFLAGS="$old_CFLAGS $smart_include"
-    SMART_CFLAGS="$SMART_CFLAGS $smart_include"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+  eval "ac_cv_header_$ac_safe=yes"
+  CFLAGS="$old_CFLAGS $smart_include"
+  SMART_CFLAGS="$SMART_CFLAGS $smart_include"
+else
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -2622,10 +2677,66 @@ ac_safe=`echo "perl.h" | sed 'y%./+-%__pm%'`
 echo "$as_me:$LINENO: checking for perl.h" >&5
 echo $ECHO_N "checking for perl.h... $ECHO_C" >&6
 
+old_CFLAGS="$CFLAGS"
 smart_include=
 smart_include_dir=
 
-  old_CFLAGS="$CFLAGS"
+if test "x$smart_try_dir" != "x"; then
+  for try in $smart_try_dir; do
+    CFLAGS="$old_CFLAGS -I$try"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <EXTERN.h>
+		    #include <perl.h>
+int
+main ()
+{
+ int a = 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  smart_include="-I$try"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+smart_include=
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+    if test "x$smart_include" != "x"; then
+      break;
+    fi
+    CFLAGS="$old_CFLAGS"
+  done
+fi
+
+if test "x$smart_include" = "x"; then
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -2671,8 +2782,9 @@ sed 's/^/| /' conftest.$ac_ext >&5
 smart_include=
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
 
-  if test "x$smart_include" = "x"; then
+if test "x$smart_include" = "x"; then
 
 
 if test "x$LOCATE" != "x"; then
@@ -2701,17 +2813,16 @@ fi
 eval "smart_include_dir=\"\$smart_include_dir $DIRS\""
 
 
-    for try in $smart_try_dir $smart_include_dir /usr/local/include/ /opt/include; do
-      CFLAGS="$old_CFLAGS -I$try"
-
-      cat >conftest.$ac_ext <<_ACEOF
+  for try in $smart_include_dir /usr/local/include /opt/include; do
+    CFLAGS="$old_CFLAGS -I$try"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 #include <EXTERN.h>
-		       #include <perl.h>
+		    #include <perl.h>
 int
 main ()
 {
@@ -2749,22 +2860,21 @@ sed 's/^/| /' conftest.$ac_ext >&5
 smart_include=
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-
-      if test "x$smart_include" != "x"; then
-        break;
-      fi
-    done
+    if test "x$smart_include" != "x"; then
+      break;
+    fi
     CFLAGS="$old_CFLAGS"
-  fi
+  done
+fi
 
-        if test "x$smart_include" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+if test "x$smart_include" != "x"; then
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    eval "ac_cv_header_$ac_safe=yes"
-    CFLAGS="$old_CFLAGS $smart_include"
-    SMART_CFLAGS="$SMART_CFLAGS $smart_include"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+  eval "ac_cv_header_$ac_safe=yes"
+  CFLAGS="$old_CFLAGS $smart_include"
+  SMART_CFLAGS="$SMART_CFLAGS $smart_include"
+else
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
diff --git a/src/modules/rlm_sql/drivers/rlm_sql_postgresql/configure b/src/modules/rlm_sql/drivers/rlm_sql_postgresql/configure
--- a/src/modules/rlm_sql/drivers/rlm_sql_postgresql/configure
+++ b/src/modules/rlm_sql/drivers/rlm_sql_postgresql/configure
@@ -2230,10 +2230,66 @@ ac_safe=`echo "libpq-fe.h" | sed 'y%./+-%__pm%'`
 echo "$as_me:$LINENO: checking for libpq-fe.h" >&5
 echo $ECHO_N "checking for libpq-fe.h... $ECHO_C" >&6
 
+old_CFLAGS="$CFLAGS"
 smart_include=
 smart_include_dir=
 
-  old_CFLAGS="$CFLAGS"
+if test "x$smart_try_dir" != "x"; then
+  for try in $smart_try_dir; do
+    CFLAGS="$old_CFLAGS -I$try"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+		    #include <libpq-fe.h>
+int
+main ()
+{
+ int a = 1;
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  smart_include="-I$try"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+smart_include=
+fi
+rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+    if test "x$smart_include" != "x"; then
+      break;
+    fi
+    CFLAGS="$old_CFLAGS"
+  done
+fi
+
+if test "x$smart_include" = "x"; then
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -2279,8 +2335,9 @@ sed 's/^/| /' conftest.$ac_ext >&5
 smart_include=
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
+fi
 
-  if test "x$smart_include" = "x"; then
+if test "x$smart_include" = "x"; then
 
 
 if test "x$LOCATE" != "x"; then
@@ -2309,17 +2366,16 @@ fi
 eval "smart_include_dir=\"\$smart_include_dir $DIRS\""
 
 
-    for try in $smart_try_dir $smart_include_dir /usr/local/include/ /opt/include; do
-      CFLAGS="$old_CFLAGS -I$try"
-
-      cat >conftest.$ac_ext <<_ACEOF
+  for try in $smart_include_dir /usr/local/include /opt/include; do
+    CFLAGS="$old_CFLAGS -I$try"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
 cat >>conftest.$ac_ext <<_ACEOF
 /* end confdefs.h.  */
 
-		       #include <libpq-fe.h>
+		    #include <libpq-fe.h>
 int
 main ()
 {
@@ -2357,22 +2413,21 @@ sed 's/^/| /' conftest.$ac_ext >&5
 smart_include=
 fi
 rm -f conftest.err conftest.$ac_objext conftest.$ac_ext
-
-      if test "x$smart_include" != "x"; then
-        break;
-      fi
-    done
+    if test "x$smart_include" != "x"; then
+      break;
+    fi
     CFLAGS="$old_CFLAGS"
-  fi
+  done
+fi
 
-        if test "x$smart_include" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+if test "x$smart_include" != "x"; then
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    eval "ac_cv_header_$ac_safe=yes"
-    CFLAGS="$old_CFLAGS $smart_include"
-    SMART_CFLAGS="$SMART_CFLAGS $smart_include"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+  eval "ac_cv_header_$ac_safe=yes"
+  CFLAGS="$old_CFLAGS $smart_include"
+  SMART_CFLAGS="$SMART_CFLAGS $smart_include"
+else
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -2388,11 +2443,66 @@ sm_func_safe=`echo "PQconnectdb" | sed 'y%./+-%__p_%'`
 echo "$as_me:$LINENO: checking for PQconnectdb in -lpq" >&5
 echo $ECHO_N "checking for PQconnectdb in -lpq... $ECHO_C" >&6
 
+old_LIBS="$LIBS"
 smart_lib=
 smart_lib_dir=
 
-  old_LIBS="$LIBS"
-  LIBS="$LIBS -lpq"
+if test "x$smart_try_dir" != "x"; then
+  for try in $smart_try_dir; do
+    LIBS="-L$try -lpq $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+extern char PQconnectdb();
+int
+main ()
+{
+ PQconnectdb()
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  smart_lib="-L$try -lpq"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
+    LIBS="$old_LIBS"
+  done
+fi
+
+if test "x$smart_lib" = "x"; then
+  LIBS="-lpq $old_LIBS"
   cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
@@ -2437,8 +2547,10 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
+  LIBS="$old_LIBS"
+fi
 
-  if test "x$smart_lib" = "x"; then
+if test "x$smart_lib" = "x"; then
 
 
 if test "x$LOCATE" != "x"; then
@@ -2494,10 +2606,9 @@ fi
 eval "smart_lib_dir=\"\$smart_lib_dir $DIRS\""
 
 
-    for try in $smart_try_dir $smart_lib_dir /usr/local/lib/ /opt/lib; do
-      LIBS="$old_LIBS -L$try -lpq"
-
-      cat >conftest.$ac_ext <<_ACEOF
+  for try in $smart_lib_dir /usr/local/lib /opt/lib; do
+    LIBS="-L$try -lpq $old_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
 /* confdefs.h.  */
 _ACEOF
 cat confdefs.h >>conftest.$ac_ext
@@ -2541,21 +2652,21 @@ sed 's/^/| /' conftest.$ac_ext >&5
 fi
 rm -f conftest.err conftest.$ac_objext \
       conftest$ac_exeext conftest.$ac_ext
-      if test "x$smart_lib" != "x"; then
-        break;
-      fi
-    done
+    if test "x$smart_lib" != "x"; then
+      break;
+    fi
     LIBS="$old_LIBS"
-  fi
+  done
+fi
 
-        if test "x$smart_lib" != "x"; then
-    echo "$as_me:$LINENO: result: yes" >&5
+if test "x$smart_lib" != "x"; then
+  echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
-    eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
-    LIBS="$old_LIBS $smart_lib"
-    SMART_LIBS="$SMART_LIBS $smart_lib"
-  else
-    echo "$as_me:$LINENO: result: no" >&5
+  eval "ac_cv_lib_${sm_lib_safe}_${sm_func_safe}=yes"
+  LIBS="$smart_lib $old_LIBS"
+  SMART_LIBS="$smart_lib $SMART_LIBS"
+else
+  echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
